package com.connellboyce.peppergarden.model;

public enum ESpecies {
    SPECIES_ANNUUM,
    SPECIES_CHINENSE,
    SPECIES_BACCATUM,
    SPECIES_FRUTESCENS,
    SPECIES_PUBESCENS,
    SPECIES_CARDENASII,
    SPECIES_CHACOENSE,
    SPECIES_EXIMIUM,
    SPECIES_FLEXUOSUM,
    SPECIES_MIRABILE,
    SPECIES_RHOMBOIDEUM,
    SPECIES_UNKNOWN
}
